Updates for CADET-Python-Simulator
fau-advanced-separations/CADET-Process pull request #147
Opened 2024-06-19 13:24 UTC by schmoelder

This PR contains some modifications of CADET-Process to run the [CADET-Python-Simulator](https://jugit.fz-juelich.de/IBG-1/ModSim/cadet/cadet-python-simulator).

Since the CADET-Python-Simulator is still very much experimental, let's see if / when we merge these changes to CADET-Process.

2024-12-05 11:27 UTC, daklauss requested changes
See comments. Otherwise a test of densities for coverage like for the ```molecular_weight``` as in
https://github.com/fau-advanced-separations/CADET-Process/blob/dev/tests/test_components.py 
would be a good thing.

2024-12-05 11:27 UTC, daklauss commented on CADETProcess/dynamicEvents/section.py
Shouldn't it be something like:
```
def __call___(self):
       return value
```
if you want to make it callable? Or what is the point here?

2024-12-05 12:30 UTC, schmoelder commented on CADETProcess/processModel/componentSystem.py
> +
Good catch, thanks! :)

2024-12-05 12:31 UTC, schmoelder commented on CADETProcess/dynamicEvents/section.py
That's one way to do it but I think this has the same effect. You could try it out for yourself. ;-)

2024-12-05 12:31 UTC, schmoelder commented on CADETProcess/processModel/componentSystem.py
> +
Do you mind fixing this and adding a test?

2024-12-05 12:40 UTC, daklauss commented on CADETProcess/processModel/componentSystem.py
> +
I can do

2024-12-05 23:54 UTC, daklauss commented on CADETProcess/dynamicEvents/section.py
Ah got it, value is a method. This actually does make sense. I tried it with simple attributes wich cannot work and was confused, thanks.

2024-12-06 00:19 UTC, daklauss commented
Oh ... i guess i shouldn't have amended my changes directly to your add densities commit until it is ready to merge ....

2024-12-06 00:19 UTC, daklauss approved these changes

2024-12-06 07:16 UTC, schmoelder commented on CADETProcess/processModel/componentSystem.py
> +        """list of float or None: The density of the subspecies."""
Can this really return None?

2024-12-06 07:25 UTC, schmoelder commented
Thanks Daniel, (almost) looks good to me, just some minor details.

Also, without wanting to overload this PR, what do you think about adding type annotations to entire module? Btw, this is something where Tools like Copilot / ChatGPT can really do the bulk of the work.

2024-12-06 09:32 UTC, daklauss commented
Added type annotations with gpt. Fixed some minor ai stuf. Review needed @schmoelder. Ready to merge afterwards.

2024-12-06 09:36 UTC, schmoelder commented on CADETProcess/processModel/componentSystem.py
> +    density : list
Hier bitte auch type annotations.

2024-12-06 09:39 UTC, schmoelder commented on CADETProcess/processModel/componentSystem.py
> +    def species(self) -> List[str]:
List -> list (seit Python 3.10) (dann muss man nicht mehr von typing importieren

2024-12-06 09:39 UTC, schmoelder commented on CADETProcess/processModel/componentSystem.py
> +    def species_indices(self) -> TypingDict[str, int]:
Ich glaube, hier kannst du einfach dict[str, int] machen.

2024-12-06 10:57 UTC, schmoelder commented on CADETProcess/processModel/componentSystem.py
>          """dict: Indices for each species."""
please also add dict[str, int] here (and in the other docstrings)

2024-12-06 11:22 UTC, schmoelder commented on CADETProcess/processModel/componentSystem.py
> +            The class or name of the component to be added.
The component instance or name of the component to be added.

2024-12-06 13:44 UTC, merged