Fix bad initial value for Yamamoto method
fau-advanced-separations/CADET-Process pull request #76
Opened 2023-12-01 14:45 UTC by ronald-jaepel

Change initial value from the automatic middle of the boundary space (500 & 500) to (1, 1), as an initial value of 500 can lead to numerical errors.

Also adapted yamamoto.py to PEP8.

2023-12-02 10:30 UTC, schmoelder requested changes
Thanks for taking care of this!

Please use separate commits for formatting and fixing issues.
In terms of style, I agree, we should probably update the entire code base with a linter such as `ruff`. There are, however some cases where I'd like to not use the default settings. E.g., I really dislike the way it uses linebreaks with parenthesis (see separate comment).

2023-12-02 10:30 UTC, schmoelder commented on CADETProcess/tools/yamamoto.py
> -    )
tbh, I like this style better.

2023-12-02 12:28 UTC, ronald-jaepel commented on CADETProcess/tools/yamamoto.py
> -    )
Alright.

2023-12-04 09:19 UTC, merged

2023-12-04 09:31 UTC, schmoelder commented
Oh, and please use the "rebase and squash" option.